<?php
if($this->isEnabled()):
	?>
	<br />&nbsp;
	<div id="estimatedDeliveryContainer">
	 <strong><?php echo $this->__('Estimated Delivery:'); ?></strong>
	 <div id="estimatedDeliveryText"><em><?php echo $this->__($this->getInitialMessage()); ?></em></div>
	</div>
	<script type="text/javascript">
	document.observe('dom:loaded',function() { 	
		updateDeliveryDate_Simple(document.getElementsByName('product')[0].value); }
	);
	</script>
	<?php
endif;
?>	